### ISSUE TITLE
How to Persist Main ModelContainer

### ISSUE THREAD

**Issue by phraxjams** [felladrin/unity3d-mvc#1]
Hi,

Since model container holds all other models and if i could persist it among various scenes, it will eliminate the need of GlobalStorage etc. How can i achieve that. My unsuccessful attempt below...

`

public class ModelContainer : MvcBehaviour 
{
	public static ModelContainer instance;
	public LeaguesManagerModel leaguesManager;
	public FixturesModel fixtures;	
	public TableModel table;

	void Awake () 
	{
		makeInstance();
	}
	
	void makeInstance () 
	{
		if(instance != null)
			Destroy(this.gameObject);
		else
		{
			instance = this;
			DontDestroyOnLoad(this.gameObject);
		}
	}

}
`

**Comment by felladrin** [comment]
Hi, @phraxjams. Thank you for using [unity3d-mvc](https://github.com/felladrin/unity3d-mvc/)!

I understand what you're trying to achieve, but it wouldn't fit, and probably won't easily work, with the current implementation of this framework.

The best solution, if you don't want to use GlobalStorage would be:
1. create a static class to hold your data while your game is running or
2. create a new mono behavior script that you'd attach to a game object and  make that game object don't be destroyed on load scenes. What, in the end, would work like using the GlobalStorage.

That's what's explained on Unity's [Writing the Game Manager](https://unity3d.com/pt/learn/tutorials/projects/2d-roguelike-tutorial/writing-game-manager) tutorial.

Using the _ModelContainer_ is not expected by the system, but if you want to do this anyway, you'll need to link the _ModelContainer_ to the _Application_ object from the next scene by listening to the Event [SceneManager.activeSceneChanged](https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager-activeSceneChanged.html). So when _ModelContainer_ receives the message that  the scene has changed, it would look for the new _Application_ object on scene and reference itself on _Application.model_ attribute. But I've never tried that, so I'm not sure if it would work.

The scene structure is a known problem of this structure, that's why I've started creating [unity3d-mvc-2](https://github.com/felladrin/unity3d-mvc-2) (not documented yet). It'll allow us to use MVC (or a similar approach) independently from what scene we are.

**Comment by phraxjams** [comment]
Hi,

Thanks for a detailed response.

Fundamentally, a model should keep the data and in our unity's mvc case we are not keeping it by default and doing workarounds like you suggested. My point is... if we still have to keep the data on an external manager then the only thing left is controller and view and then i start thinking to stop using MVC which i dont want. Yes i will go for a workaround and will see how things will go.

Secondly, Thanks for the mvc-2, it looks promising, i would request you to please spare few minutes and write its brief documentation, i would love to experiment with that, too.

Thanks again

**Comment by felladrin** [comment]
Sure! I'll write a  brief documentation for mvc-2 as soon as possible. Thanks for your feedback!
